### ISSUE TITLE
Textarea: only works with class="required"

### ISSUE THREAD

**Issue by stewartjohnson** [carolineschnapp/cart-attributes-validation#1]
I just applied this to my store tonight, and it ignores textareas with the html5 required attribute. If I add a css class "required" to the textarea it works fine.

**Comment by carolineschnapp** [comment]
Thanks for reporting this, Stewart. I need to spend an entire day sorting everything out — and refactoring the module. I removed any mention of it for the time being from the Shopify Wiki.
